### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by robmarkcole** [klauer/aerotech#2]
HI @klauer  thanks for posting this. Am getting it up and running in our lab using jupyter notebooks and happy to report back progress + add to docs.
Cheers

**Comment by klauer** [comment]
Hi @robmarkcole - great! I hope the project will be of some use to you. It's in a basic form now, but I'll be adding to it off and on as our facility ramps up its usage of Ensemble drives.

**Comment by robmarkcole** [comment]
I've forked off in a slightly different direction, not using asyncio for the time being. You may find the Emulator useful (developed by a colleague).
Cheers

https://github.com/robmarkcole/aerotech

**Comment by klauer** [comment]
Best of luck to you, @robmarkcole! Perhaps we can share ideas between the projects at some point.
